version: '2'

services:
    nginx:
        build:
            context: ./docker/nginx
        volumes_from:
            - volumes
        ports:
            - "80:80"
            - "443:443"

        depends_on:
          - node

    node:
        build:
          context: ./node_app
          args:
              - PROJECT_PATH=/usr/src/app
        volumes:
            # dont know if mount volumn using `.:/usr/src ` would cause some wired consequenses
            # since current dir has some volume already mounted in other kind of form
            - ./node_app/build/:/usr/src/app/build
        environment:
          - NODE_PORT=8080
          - MYSQL_CONNECTION_HOST=mysql
          - MYSQL_DATABASE=myapp_dev
          - MYSQL_USER=node_app_user
          - MYSQL_PASSWORD=jkliop
          
        depends_on:
          - mysql


    mysql:
        build:
            context: ./docker/mysql
            args:
                - MYSQL_DATABASE=myapp_dev
                - MYSQL_USER=node_app_user
                - MYSQL_PASSWORD=jkliop
                - MYSQL_ROOT_PASSWORD=root
        volumes_from:
            - volumes
        expose:
            - "3306"


    # mongo:
    #     build: ./docker/mongo
    #     expose:
    #         - "27017"
    #     volumes_from:
    #         - volumes

    # redis:
    #   image: redis:3

    volumes:
        image: tianon/true
        volumes:
            # - ./data/mongo:/var/lib/mongodb
            - ./data/logs/nginx/:/var/log/nginx
            - ./data/mysql:/var/lib/mysql
