version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: make run
    ports:
     - "9000:9000"
    volumes:
     - .:/code
     # exclude node_modules from volumes, for more info view: https://www.youtube.com/watch?v=zcSbOl8DYXM
     # so that mac node binaries doesnt colide with linux node binaries
     # create a named volumn
     - api_deps:/code/node_modules
    
volumes:
  api_deps:
